# -*- coding: utf-8 -*-
"""Confeitaria - MRP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qu-7MOc6FURJxn0bXVjQAYEsUlPDeo4a
"""

import matplotlib.pyplot as plt
from datetime import datetime
from tabulate import tabulate
import sqlite3

conn = sqlite3.connect('estoque_produtos.db')
cursor = conn.cursor()

cursor.execute("""
  CREATE TABLE IF NOT EXISTS produtos(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    preco REAL NOT NULL,
    quantidade REAL NOT NULL,
    categoria TEXT NOT NULL,
    unidade TEXT NOT NULL)""")
conn.commit()

cursor.execute("""
CREATE TABLE IF NOT EXISTS movimentacoes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produto_id INTEGER NOT NULL,
    quantidade REAL NOT NULL,
    tipo TEXT NOT NULL,
    data_movimentacao TEXT NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES produtos(id)
)
""")
conn.commit()


print("✶.° Confeitaria Lumiere 🍰")

def cadastrar_produto():
  nome_produto = input("Nome do produto: ").capitalize()
  preco_produto = float(input("Preço do produto: "))
  quantidade_produto = float(input("Quantidade do produto: "))
  categoria_produto = input("Categoria do produto: \n• Material de produção (MP) \n• Produto pronto (PP) \n• Embalagem (EMB) \n• Insumos (INS)\n").upper()
  unidade_produto = input("Unidade do produto: \n• Quilos (KG) \n• Litros (L) \n• Unidades (UN) \n• Caixas (CX)\n").upper()

  cursor.execute("INSERT INTO produtos (nome, preco, quantidade, categoria, unidade) VALUES (?, ?, ?, ?, ?)", (nome_produto, preco_produto, quantidade_produto, categoria_produto, unidade_produto))
  conn.commit()
  print(f"O produto {nome_produto} foi cadastrado com sucesso!")

def listar_produto():
  cursor.execute("SELECT * FROM produtos")
  produtos = cursor.fetchall()
  if not produtos:
    print("Não há produtos cadastrados.")
    return
  else:
    print("Produtos cadastrados: \n")
    tabela = []
    for produto in produtos[::-1]:
        valor_total = produto[2]*produto[3]
        tabela.append([produto[0], produto[1], f"R${produto[2]:.2f}", produto[3], produto[4], produto[5], f"R${valor_total:.2f}"])

    print(tabulate(tabela, headers=["ID", "Nome", "Preço", "Qtd", "Cat", "Unidade", "Valor Total"], tablefmt="fancy_grid"))
    print("\n")
    for produto in produtos[::-1]:
        if produto[3] < 5:
            print(f"⚠ Estoque baixo: {produto[1]} - apenas {produto[3]} unidades de {produto[5]}")

def buscar_produto():
  nome_busca = input("Digite o nome do produto desejado: ").capitalize()
  cursor.execute("SELECT * FROM produtos WHERE nome LIKE ?", (f"%{nome_busca}%",))
  resultados = cursor.fetchall()

  if not resultados:
    print("Nenhum produto encontrado com esse nome.\n")

  else:
    print("Produtos(s) encontrado(s): \n")
    for produto in resultados:
      valor_total = produto[2]*produto[3]
      print(f"""
      ID: {produto[0]}
      Nome: {produto[1]}
      Preço unitário: R${produto[2]:.2f}
      Quantidade: {produto[3]}
      Categoria: {produto[4]}
      Unidade: {produto[5]}
      Valor total: R${valor_total:.2f}""")

def excluir_produto():
  cursor.execute("SELECT * FROM produtos")
  produtos = cursor.fetchall()
  for produto in produtos:
    print(f"{produto[0]} - {produto[1]}")
  id_excluir = int(input("Digite o ID do produto que deseja excluir: "))
  cursor.execute("SELECT * FROM produtos WHERE id = ?", (id_excluir,))
  produto_excluir = cursor.fetchone()
  if not produto_excluir:
    print("Produto não encontrado.\n")
  else:
    cursor.execute("DELETE FROM produtos WHERE id = ?", (id_excluir,))
    conn.commit()
    print(f"Produto {produto_excluir[1]} excluído com sucesso!\n")

def movimentar_produto():
  cursor.execute("SELECT * FROM produtos")
  produtos = cursor.fetchall()
  for produto in produtos:
    print(f"{produto[0]} - {produto[1]}")
  id_produto = int(input("Digite o ID do produto que deseja movimentar: "))
  cursor.execute("SELECT * FROM produtos WHERE id = ?", (id_produto,))
  produto_movimentar = cursor.fetchone()
  if not produto_movimentar:
    print("Produto não encontrado.\n")

  else:
    nome, preco, quantidade = produto_movimentar[1], produto_movimentar[2], produto_movimentar[3]
    print("Produto encontrado: ")
    print(f"Nome: {nome}")
    print(f"Preço: R${preco:.2f}")
    print(f"Quantidade: {quantidade}")

    try:
      print("""Selecione uma das opções de movimentação:
      1. Entrada de estoque (adicionar)
      2. Saída de estoque (remover)""")
      opcao_movimentacao = int(input("Digite a opção desejada: "))
    except ValueError:
      print("Opção inválida. Tente novamente.")
      return

    if opcao_movimentacao == 1:
      quantidade_entrada = float(input("Digite a quantidade a ser adicionada: "))
      nova_quantidade = quantidade + quantidade_entrada
      cursor.execute("UPDATE produtos SET quantidade = ? WHERE id = ?", (nova_quantidade, id_produto))
      cursor.execute("INSERT INTO movimentacoes (produto_id, quantidade, tipo, data_movimentacao) VALUES (?, ?, ?, ?)",
      (id_produto, quantidade_entrada, "entrada", datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
      conn.commit()
      print(f"A quantidade do produto {nome} foi atualizada para {nova_quantidade}.")

    elif opcao_movimentacao == 2:
      quantidade_saida = float(input("Digite a quantidade a ser removida: "))
      if quantidade_saida > quantidade:
        print("Quantidade insuficiente em estoque.")
        return
      else:
        nova_quantidade = quantidade - quantidade_saida
        cursor.execute("UPDATE produtos SET quantidade = ? WHERE id = ?", (nova_quantidade, id_produto))
        cursor.execute("INSERT INTO movimentacoes (produto_id, quantidade, tipo, data_movimentacao) VALUES (?, ?, ?, ?)",
            (id_produto, quantidade_saida, "saida", datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
        conn.commit()
        print(f"A quantidade do produto {nome} foi atualizada para {nova_quantidade}.")

    else:
      print("Opção inválida. Tente novamente.")

def giros_estoque():
  cursor.execute("SELECT id, nome, quantidade FROM produtos")
  produto_giro = cursor.fetchall()

  if not produto_giro:
    print("Nenhum produto cadastrado.\n")
    return

  else:
    print("Giro de Estoque\n")
    for produto_id, nome, estoque_atual in produto_giro:
      cursor.execute("SELECT SUM(quantidade) FROM movimentacoes WHERE produto_id = ? AND tipo = 'saida'", (produto_id,))
      total_saida = cursor.fetchone()[0] or 0

      cursor.execute("SELECT data_movimentacao FROM movimentacoes WHERE produto_id = ? ORDER BY data_movimentacao DESC LIMIT 1", (produto_id,))
      ultima_mov = cursor.fetchone()

      data = "Nenhuma movimentação" # Default value if no movements
      if ultima_mov:
        data_obj = datetime.strptime(ultima_mov[0], "%Y-%m-%d %H:%M:%S")
        data = data_obj.strftime("%d/%m/%Y")

      estoque_medio = estoque_atual
      giro = total_saida / estoque_medio if estoque_medio > 0 else 0
      print(f"""{nome}:
      Giro de estoque = {giro:.2f}
      Estoque atual: {estoque_atual}
      Total de saídas: {total_saida}
      Última movimentação: {data}\n""")

def custo_manutencao(percentual=0.08):
  cursor.execute("SELECT nome, preco, quantidade FROM produtos")
  produto_custo = cursor.fetchall()

  print("Custo de Manutenção do Estoque\n")
  for nome, preco, quantidade in produto_custo:
      custo = preco * quantidade * percentual
      print(f"Manutenção: {preco}x{quantidade}x{percentual}")
      print(f"{nome} - Custo médio para manter o estoque: R${custo:.2f}")

def tempo_medio_reposicao():
  cursor.execute("SELECT produto_id, MIN(data_movimentacao), MAX(data_movimentacao) FROM movimentacoes WHERE tipo='saida' GROUP BY produto_id")
  registros = cursor.fetchall()

  print("Tempo Médio de Reposição\n")
  for produto_id, primeira, ultima in registros:
      cursor.execute("SELECT nome FROM produtos WHERE id=?", (produto_id,))
      nome = cursor.fetchone()[0]
      if primeira and ultima:
          data_ini = datetime.strptime(primeira, "%Y-%m-%d %H:%M:%S")
          data_fim = datetime.strptime(ultima, "%Y-%m-%d %H:%M:%S")
          dias = (data_fim - data_ini).days
          print(f"{nome}: {dias} dias entre primeira e última saída")
      else:
          print(f"{nome}: sem movimentações")

def grafico_linha():
    cursor.execute("SELECT data_movimentacao, tipo, quantidade FROM movimentacoes ORDER BY data_movimentacao")
    dados = cursor.fetchall()

    if not dados:
        print("Nenhuma movimentação encontrada.")
        return

    datas = []
    entradas = []
    saídas = []

    for data, tipo, qtd in dados:
        data_formatada = datetime.strptime(data, "%Y-%m-%d %H:%M:%S").strftime("%d/%m")
        datas.append(data_formatada)

        if tipo == "entrada":
            entradas.append(qtd)
            saídas.append(0)
        elif tipo == "saida":
            saídas.append(qtd)
            entradas.append(0)
        else:
            entradas.append(0)
            saídas.append(0)

    plt.plot(datas, entradas, label="Entradas", color="green")
    plt.plot(datas, saídas, label="Saídas", color="red")

    ax = plt.gca()
    ax.set_facecolor("lightyellow")

    plt.title("Movimentação de Estoque")
    plt.xlabel("Dias")
    plt.ylabel("Quantidade")
    plt.legend()
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

def grafico_barra():
  cursor.execute("SELECT nome, quantidade FROM produtos")
  produtos = cursor.fetchall()

  if not produtos:
      print("Nenhum produto encontrado.")
      return

  nomes = [p[0] for p in produtos]
  quantidades = [p[1] for p in produtos]

  plt.bar(nomes, quantidades, color="pink")

  ax = plt.gca()
  ax.set_facecolor("lavender")

  plt.title("Estoque por Produto")
  plt.xlabel("Produtos")
  plt.ylabel("Quantidade")
  plt.xticks(rotation=60, ha="right")
  plt.tight_layout()
  plt.show()


# Ações -----------------

while True:
  print("""
  Menu de opções:
  1. Cadastrar
  2. Listar
  3. Buscar
  4. Excluir
  5. Movimentação
  6. Giro de estoque
  7. Custo de manutenção
  8. Tempo médio de reposição
  9. Dashboard Gráfico de linha
  10. Dashboard Gráfico de barra
  0. Sair""")

  try:
    opcao_menu = int(input("\nDigite a opção desejada: "))
  except ValueError:
    print("Opção inválida. Tente novamente.")
    continue

  match opcao_menu:
    case 1:
      print("Opção 1 - Cadastrar\n")
      try:
        cadastrar_produto()
      except ValueError:
        print("Um dos valores foi inserido incorretamente. Tente novamente.")

    case 2:
      print("Opção 2 - Listar\n")
      listar_produto()

    case 3:
      print("Opção 3 - Buscar\n")
      buscar_produto()

    case 4:
      print("Opção 4 - Excluir\n")
      excluir_produto()

    case 5:
      print("Opção 5 - Movimentação\n")
      movimentar_produto()

    case 6:
      print("Opção 6 - Giro de estoque\n")
      giros_estoque()

    case 7:
      print("Opção 7 - Custo de manutenção\n")
      custo_manutencao()

    case 8:
      print("Opção 8 - Tempo médio de reposição\n")
      tempo_medio_reposicao()

    case 9:
      print("Opção 9 - Dashboard gráfico de linha\n")
      grafico_linha()

    case 10:
      print("Opção 10 - Dashboard gráfico de barra\n")
      grafico_barra()

    case 0:
      print("Saindo do sistema...")
      break

    case _:
      print("Opção inválida. Tente novamente.")